'use strict';
(()=>{
 const $=s=>document.querySelector(s),view=$('#view'),hud=$('#hud'),app=$('#app');
 const icons={play:'<path d="m9 5 12 7-12 7Z"/>',back:'<path d="m14 5-7 7 7 7"/>',home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',restart:'<path d="M3 10a9 9 0 1 1 2 9M3 3v7h7"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',trophy:'<path d="M8 3h8v7a4 4 0 0 1-8 0ZM8 5H4v3a4 4 0 0 0 4 4M16 5h4v3a4 4 0 0 1-4 4M12 14v6M8 21h8"/>',book:'<path d="M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-4-2-7-1-10 1v15"/>',settings:'<path d="m9 3-1 3-3 1v4l2 1v2l-2 2 2 3 3-1 2 3 3-1 1-3 3-1v-4l-2-1v-2l2-2-2-3-3 1-2-3Z"/><circle cx="12" cy="12" r="3"/>',heart:'<path d="M12 21 3 12C-2 5 7-1 12 6c5-7 14-1 9 6Z"/>',sound:'<path d="m3 9 5 0 5-5v16l-5-5H3ZM17 8a6 6 0 0 1 0 8M20 5a10 10 0 0 1 0 14"/>',music:'<path d="M9 17V5l12-2v12M9 8l12-2"/><ellipse cx="5" cy="18" rx="4" ry="3"/><ellipse cx="17" cy="16" rx="4" ry="3"/>',tap:'<path d="M9 12V5a2 2 0 0 1 4 0v7l2-3 6 3-1 7-4 3h-5L4 14a2 2 0 0 1 3-2l2 2"/>',check:'<path d="m4 12 5 5L20 6"/>',star:'<path d="m12 2 3 7 8 1-6 5 2 8-7-4-7 4 2-8-6-5 8-1Z"/>'};
 const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.star}</svg>`;
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let saved={};try{const value=JSON.parse(localStorage.getItem('estrella-v1')||'{}');if(value&&typeof value==='object'&&!Array.isArray(value))saved=value}catch{}
 const names=['Amir','Florencia','Angela','Aline'],roles=['Auxiliar de Enfermería','Auxiliar de Enfermería','Licenciada · Jefa de Emergencia','Auxiliar de Enfermería'];
 let selected=Number.isInteger(saved.selected)&&saved.selected>=0&&saved.selected<4?saved.selected:0,sound=saved.sound!==false,music=saved.music!==false,name=typeof saved.name==='string'?saved.name.slice(0,18):'Amir';
 let records=Array.isArray(saved.records)?saved.records.filter(r=>r&&typeof r.name==='string'&&names.includes(r.character)&&Number.isFinite(r.score)&&r.score>=0).sort((a,b)=>b.score-a.score).slice(0,20):[];
 let state='loading',lastResult={score:0,hearts:0},newRecord=false,engine,loadingError='';
 const audio=new GuardiaAudio();audio.settings(sound,music);
 const persist=()=>{try{localStorage.setItem('estrella-v1',JSON.stringify({selected,sound,music,name,records}))}catch{$('#announcement').textContent='No se pudo guardar el récord en este navegador.'}};
 const best=()=>records.reduce((v,r)=>Math.max(v,r.score),0);
 const button=(action,text,kind='secondary',ico='')=>`<button class="button button-${kind}" data-action="${action}">${ico?icon(ico):''}<span>${text}</span>${kind==='primary'?'<span class="button-arrow" aria-hidden="true">›</span>':''}</button>`;
 const top=(title,kicker='GRUPO ESTRELLA')=>`<header class="topbar"><button class="icon-button" data-action="menu" aria-label="Volver al menú">${icon('back')}</button><div><p class="eyebrow">${kicker}</p><h1 class="topbar-title" tabindex="-1">${title}</h1></div><span class="topbar-spacer"></span></header>`;
 const portrait=(id,cls='')=>`<canvas class="portrait ${cls}" data-portrait="${id}" role="img" aria-label="${names[id]}"></canvas>`;
 function render(html,next,focus=true){state=next;view.hidden=false;view.innerHTML=`<section class="screen-inner ${next}-screen">${html}</section>`;view.dataset.screen=next;app.dataset.state=next;hud.hidden=next!=='playing';audio.setMode(next);drawPortraits();if(focus)view.querySelector('h1, h2, button')?.focus({preventScroll:true});view.scrollTop=0}
 function drawPortraits(){view.querySelectorAll('[data-portrait]').forEach(c=>engine?.renderPortrait(c,+c.dataset.portrait))}
 function menu(){engine?.stop();render(`<div class="menu-top"><span class="edition-label"><i></i> LA GUARDIA EMPIEZA ACÁ</span><button class="icon-button" data-action="settings" aria-label="Abrir ajustes">${icon('settings')}</button></div><div class="hero-logo" role="heading" aria-level="1"><span class="logo-small">GRUPO</span><span class="logo-main">ESTRELLA</span><span class="logo-sub">FLAPPY GUARDIA</span><span class="logo-code"><i></i>CÓDIGO ROJO<i></i></span></div><div class="menu-team">${portrait(selected)}<div><span class="eyebrow">EN ESTA GUARDIA</span><strong>${names[selected]}</strong><button class="text-button" data-action="characters">Cambiar personaje ${icon('back')}</button></div></div><nav class="menu-actions" aria-label="Menú principal">${button('ready','JUGAR','primary','play')}<div class="menu-action-grid">${button('characters','Personajes','secondary','people')}${button('records','Récords','secondary','trophy')}${button('instructions','Cómo jugar','secondary','book')}${button('credits','Créditos','secondary','star')}</div></nav><footer class="menu-footer"><span>${icon('trophy')} Récord <b>${best()}</b></span><p>Mismas personas. Mismas locuras.<br><strong>Mejores guardias.</strong></p><small>v3.0</small></footer>`,'menu',false)}
 function characters(){render(`${top('Elegí tu personaje')}<p class="screen-intro">Cuatro formas de llevar la guardia.<br>Una estrella para cada partida.</p><div class="character-grid">${names.map((n,i)=>`<button class="character-card character-${i} ${selected===i?'is-selected':''}" data-character="${i}" aria-pressed="${selected===i}">${selected===i?`<span class="selected-mark">${icon('check')}</span>`:''}${portrait(i)}<span class="character-name">${n}</span><span class="character-role">${i===2?'LA JEFA':'EQUIPO EMERGENCIA'}</span></button>`).join('')}</div><div class="panel character-detail"><span class="eyebrow">TU PERSONAJE</span><h2>${names[selected]}</h2><p>${roles[selected]}</p><p class="character-quote">“${['Siempre en movimiento','Una sonrisa en cada guardia','La jefa siempre está','La energía del equipo'][selected]}”</p><span class="detail-note">${icon('check')} Selección guardada</span></div><div class="sticky-actions">${button('ready','A LA GUARDIA','primary','play')}</div>`,'characters')}
 function ready(){engine.stop();engine.setCharacter(selected);render(`${top('¿Listo para la guardia?')}<div class="ready-stage">${portrait(selected)}<div class="tap-indicator">${icon('tap')}</div></div><div class="ready-copy"><span class="eyebrow">${names[selected].toUpperCase()} ESTÁ LISTO</span><h2>Un toque.<br>Un salto.</h2><p>Pasá entre las jeringas.<br>Recogé corazones y superá tu récord.</p></div><div class="sticky-actions">${button('start','EMPEZAR','primary','play')}<p class="keyboard-hint">En computadora: espacio o ↑</p></div>`,'ready')}
 function start(){state='playing';view.hidden=true;app.dataset.state='playing';hud.hidden=false;$('#score').textContent='0';$('#heartCount').textContent='0 corazones';audio.setMode('playing');engine.setCharacter(selected);engine.start();$('#gameCanvas').focus({preventScroll:true})}
 function pause(){if(state!=='playing')return;engine.pause()}
 function pauseScreen(){render(`<div class="pause-ornament" aria-hidden="true">☕</div><span class="eyebrow">LA GUARDIA PUEDE ESPERAR</span><h1 class="screen-heading" tabindex="-1">PAUSA</h1><p class="screen-intro">Un respiro también<br>es parte de la guardia.</p><div class="pause-score"><span>Puntos</span><strong>${$('#score').textContent}</strong></div><div class="menu-actions">${button('resume','CONTINUAR','primary','play')}${button('ready','Reiniciar','secondary','restart')}</div>${toggles()}${button('menu','Volver al menú','ghost','home')}`,'paused')}
 function resume(){state='playing';view.hidden=true;app.dataset.state='playing';hud.hidden=false;audio.setMode('playing');engine.resume();$('#gameCanvas').focus({preventScroll:true})}
 function toggles(){return `<div class="panel settings-panel"><label class="toggle-row"><span>${icon('sound')}<span>Sonido<small>Saltos, corazones y puntos</small></span></span><input type="checkbox" data-setting="sound" ${sound?'checked':''}><i class="switch-track" aria-hidden="true"></i></label><label class="toggle-row"><span>${icon('music')}<span>Música<small>La melodía de la guardia</small></span></span><input type="checkbox" data-setting="music" ${music?'checked':''}><i class="switch-track" aria-hidden="true"></i></label></div>`}
 function settings(){render(`${top('Ajustes')}<div class="settings-hero">${icon('settings')}</div><h2 class="screen-heading">Tu guardia.<br>A tu ritmo.</h2>${toggles()}<p class="screen-intro">El sonido comienza después de tu primer toque.</p>${button('menu','LISTO','primary','check')}`,'settings')}
 function recordsPage(){render(`${top('Récords')}<div class="record-hero"><span>${icon('trophy')}</span><div><span class="eyebrow">TU MEJOR GUARDIA</span><strong>${best()}</strong><small>PUNTOS</small></div></div><div class="records-caption"><h2>Las mejores partidas</h2><span>Este dispositivo</span></div><div class="panel table-panel">${records.length?`<table class="score-table"><thead><tr><th>#</th><th>Nombre</th><th>Personaje</th><th>Puntos</th></tr></thead><tbody>${records.slice(0,10).map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td><span class="table-character">${portrait(names.indexOf(r.character))}<span>${r.character}</span></span></td><td>${r.score}</td></tr>`).join('')}</tbody></table>`:`<div class="empty-records">${icon('trophy')}<h3>El primer récord puede ser tuyo.</h3><p>Jugá una partida para inaugurar la tabla.</p></div>`}</div><label class="name-field">Tu nombre<input id="playerName" maxlength="18" value="${esc(name)}" autocomplete="nickname" placeholder="Tu nombre"></label><p class="keyboard-hint">Las partidas se guardan en este navegador.</p><div class="sticky-actions">${button('ready','JUGAR','primary','play')}</div>`,'records')}
 function instructions(){const rows=[['tap','Tocá para saltar','Cada toque te impulsa. Soltá para bajar.'],['play','Encontrá el hueco','Evitá las jeringas, el techo y el piso.'],['heart','Sumá corazones','Cada corazón vale 3 puntos. Pasar una pareja de jeringas suma 1.'],['trophy','Superá tu récord','La guardia se vuelve más rápida de a poco.'],['people','Elegí tu estrella','Las caras del equipo te acompañan en cada partida.']];render(`${top('Cómo jugar')}<div class="instruction-heading"><span class="eyebrow">FÁCIL DE JUGAR</span><h2>Difícil de soltar.</h2></div><ol class="instruction-list">${rows.map(([ic,t,d],i)=>`<li><span class="instruction-icon">${icon(ic)}</span><div><small>0${i+1}</small><h3>${t}</h3><p>${d}</p></div></li>`).join('')}</ol><div class="panel keyboard-panel"><span>COMPUTADORA</span><p><kbd>Espacio</kbd> o <kbd>↑</kbd> para saltar<br><kbd>P</kbd> o <kbd>Esc</kbd> para pausar</p></div><div class="sticky-actions">${button('ready','¡ENTENDIDO, A JUGAR!','primary','play')}</div>`,'instructions')}
 function credits(){render(`${top('Créditos')}<div class="credits-star">${icon('star')}</div><h2 class="screen-heading">GRUPO<br>ESTRELLA</h2><p class="screen-intro">El equipo que hace<br>la guardia más llevadera.</p><div class="panel credits-list"><div><span>IDEA ORIGINAL</span><strong>Amir</strong></div><div><span>EL EQUIPO</span><strong>Amir · Florencia<br>Angela · Aline</strong></div><div><span>DISEÑO Y DESARROLLO</span><strong>Grupo Estrella Games</strong><p>Creado con asistencia de IA.</p></div><div><span>ARTE</span><p>Personajes de la referencia de Amir.<br>Interfaz y controles reconstruidos para el juego.</p></div></div><p class="credits-thanks">“La guardia también se disfruta.” ♡</p>${button('menu','VOLVER AL MENÚ','secondary','home')}<p class="keyboard-hint">Flappy Guardia · Código Rojo · v3.0</p>`,'credits')}
 function gameover(result){lastResult=result;newRecord=result.score>best();records.push({name:name.trim()||names[selected],character:names[selected],score:result.score,date:Date.now()});records.sort((a,b)=>b.score-a.score);records=records.slice(0,20);persist();audio.setMode('over');render(`<span class="eyebrow">${newRecord?'UNA GUARDIA PARA RECORDAR':'LA GUARDIA SIGUE'}</span><h1 class="gameover-title" tabindex="-1">GAME<br><em>OVER</em></h1><div class="result-character">${portrait(selected)}<span class="result-bubble">${newRecord?'¡Nueva estrella!':'Casi…'}</span></div><div class="result-grid"><div><span>PUNTOS</span><strong>${result.score}</strong></div><div class="result-best"><span>${icon('trophy')} RÉCORD</span><strong>${best()}</strong></div></div><p class="result-note">${newRecord?'¡Superaste tu mejor partida!':'La próxima es mejor. ♡'}<small>${result.hearts} ${result.hearts===1?'corazón recogido':'corazones recogidos'}</small></p><div class="sticky-actions">${button('ready','JUGAR DE NUEVO','primary','restart')}${button('characters','Cambiar personaje','secondary','people')}${button('menu','Volver al menú','ghost','home')}</div>`,'over');$('#announcement').textContent=`Fin de partida: ${result.score} puntos.`}
 const actions={menu,characters,ready,start,pause,resume,settings,records:recordsPage,instructions,credits,retry:()=>location.reload()};
 view.addEventListener('click',e=>{const c=e.target.closest('[data-character]'),b=e.target.closest('[data-action]');if(!c&&!b)return;audio.unlock();audio.play('click');if(c){selected=+c.dataset.character;persist();characters();view.querySelector(`[data-character="${selected}"]`)?.focus({preventScroll:true});return}actions[b.dataset.action]?.()});
 view.addEventListener('change',e=>{const setting=e.target.dataset.setting;if(!setting)return;if(setting==='sound')sound=e.target.checked;if(setting==='music')music=e.target.checked;audio.unlock();audio.settings(sound,music);persist()});
 view.addEventListener('input',e=>{if(e.target.id==='playerName'){name=e.target.value;persist()}});
 $('#pauseButton').addEventListener('click',pause);
 $('#gameCanvas').addEventListener('pointerdown',e=>{if(state!=='playing'||engine.state!=='playing')return;e.preventDefault();audio.unlock();engine.flap();audio.play('flap')});
 document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||e.repeat)return;if(e.code==='KeyP'||e.code==='Escape'){if(state==='playing'){e.preventDefault();pause()}else if(state==='paused'){e.preventDefault();resume()}return}if(e.target.matches('button,a'))return;if(['Space','ArrowUp'].includes(e.code)){if(state==='playing'&&engine.state==='playing'){e.preventDefault();engine.flap();audio.play('flap')}else if(state==='ready'){e.preventDefault();audio.unlock();start()}}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();audio.suspend()}});
 async function boot(){try{engine=new GuardiaEngine($('#gameCanvas'),{onScore:r=>{const before=+$('#score').textContent;$('#score').textContent=r.score;$('#heartCount').textContent=`${r.hearts} ${r.hearts===1?'corazón':'corazones'}`;if(r.score>before)audio.play(r.score-before===3?'heart':'point')},onGameOver:gameover,onHit:()=>audio.play('hit'),onPause:()=>{if(state==='playing')pauseScreen()}});await engine.ready;menu()}catch(err){loadingError=String(err);render(`<div class="loading-star">!</div><h1 tabindex="-1">No pudimos cargar al equipo</h1><p>Revisá la conexión y volvé a intentarlo.</p>${button('retry','REINTENTAR','primary','restart')}`,'error')}}
 // Prompt an installed legacy worker to fetch its one-time retirement script.
 if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.getRegistrations().then(list=>{const scope=new URL('./',location.href).href;for(const r of list)if(r.scope===scope&&r.active?.scriptURL===new URL('sw.js',scope).href)r.update().catch(()=>{});}).catch(()=>{});
 boot();
})();
