'use strict';
(() => {
const $=s=>document.querySelector(s), app=$('#app'), screen=$('#screen'), canvas=$('#game'), ctx=canvas.getContext('2d');
const source=new Image(); source.src='assets/reference.png';
const chars=[
 {name:'Amir',line:'Siempre en movimiento',crop:[283,151,111,138],head:[285,155,109,121],points:[[3,47],[9,26],[29,10],[55,0],[83,8],[96,23],[98,45],[96,65],[85,81],[72,95],[57,104],[43,97],[25,87],[14,64]],stats:[65,73,50],gravity:900,jump:324},
 {name:'Florencia',line:'Una sonrisa en cada guardia',crop:[405,151,106,138],head:[406,157,103,129],points:[[0,68],[7,36],[20,13],[41,0],[65,2],[84,16],[96,38],[101,83],[98,119],[82,120],[69,101],[50,107],[28,96],[17,121],[4,117]],stats:[57,83,64],gravity:840,jump:313},
 {name:'Angela',line:'La jefa siempre está',crop:[284,331,109,137],head:[285,333,109,133],points:[[0,128],[0,61],[5,32],[19,14],[40,0],[67,0],[88,11],[101,36],[108,72],[105,126],[89,126],[81,107],[77,94],[69,104],[56,110],[46,108],[36,97],[28,87],[25,128],[14,133]],stats:[53,70,90],gravity:860,jump:317},
 {name:'Aline',line:'La energía del equipo',crop:[406,331,105,137],head:[409,334,99,128],points:[[2,107],[0,69],[3,36],[17,13],[39,1],[61,1],[80,12],[92,33],[97,62],[92,87],[74,103],[61,110],[47,106],[34,97],[25,84],[23,110],[13,113],[4,107]],stats:[75,65,72],gravity:920,jump:328}
];
let saved={};try{saved=JSON.parse(localStorage.getItem('estrella-v1')||'{}')}catch{}
let selected=Number.isInteger(saved.selected)&&saved.selected>=0&&saved.selected<4?saved.selected:0;
let sound=saved.sound!==false,music=saved.music!==false,name=typeof saved.name==='string'?saved.name.slice(0,18):'Amir';
let records=Array.isArray(saved.records)?saved.records.filter(r=>r&&typeof r.name==='string'&&typeof r.character==='string'&&Number.isFinite(r.score)).slice(0,20):[];
const persist=()=>{try{localStorage.setItem('estrella-v1',JSON.stringify({selected,sound,music,name,records}))}catch{}};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state='loading',W=390,H=780,last=0,time=0,player,obstacles=[],particles=[],score=0,hearts=0,spawn=0,elapsed=0,shake=0,audio,melodyTimer,beat=0,readyAt=0;
function fit(){const r=app.getBoundingClientRect();W=390;H=Math.max(390,390*r.height/r.width);const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
new ResizeObserver(()=>{fit();if(state==='playing')pause()}).observe(app);fit();
function audioInit(){try{audio||=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();if(!melodyTimer)melodyTimer=setInterval(()=>{if(!music||document.hidden||!audio)return;const notes=[523.25,0,659.25,783.99,0,659.25,587.33,0];tone(notes[beat++%notes.length],.13,.022,'sine',true);if(beat%8===1)tone(1046,.08,.013,'sine',true)},340)}catch{}}
function tone(f,d=.1,v=.07,type='sine',isMusic=false){if(!f||!audio||audio.state!=='running'||(!isMusic&&!sound))return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(v,audio.currentTime+.012);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}
const sprites={play:[41,449,196,58],characters:[41,513,196,49],records:[41,566,196,44],instructions:[41,613,196,49],credits:[74,663,162,43],continue:[293,704,214,55],resume:[813,300,191,55],restart:[813,362,191,52],sound:[813,421,191,55],music:[813,480,191,55],home:[813,539,191,57],again:[23,1307,217,55],overHome:[23,1365,217,53]};
function art(rect,cls='',label=''){return `<canvas class="art ${cls}" data-art="${rect.join(',')}" ${label?`role="img" aria-label="${label}"`:'aria-hidden="true"'}></canvas>`}
function btn(action,text,icon='',primary=false){const key=action==='ready'?(text==='JUGAR DE NUEVO'?'again':text==='CONTINUAR'?'continue':'play'):({menu:'home',start:'play',resume:'resume',characters:'characters',records:'records',instructions:'instructions',credits:'credits'}[action]);return key?`<button class="sprite-button ${primary?'primary':''}" data-action="${action}" aria-label="${text}">${art(sprites[key])}<span class="sr-only">${text}</span></button>`:`<button class="btn" data-action="${action}">${text}</button>`}
function top(title){const plain=title.replace(/<br>/g,' ');return `<header class="top"><button class="back" data-action="menu" aria-label="Volver al menú">‹</button><h1>${title}</h1></header>`}
function toggle(key,label){const on=key==='sound'?sound:music;return `<button class="sprite-button toggle" data-action="${key}" role="switch" aria-label="${label}" aria-checked="${on}">${art(sprites[key])}<span class="real-switch ${on?'on':''}" aria-hidden="true"></span></button>`}
function crop(c,rect){c.width=rect[2]*2;c.height=rect[3]*2;c.getContext('2d').drawImage(source,...rect,0,0,c.width,c.height)}
function head(g,id,x,y,size,rotation=0){const ch=chars[id];g.save();g.translate(x,y);g.rotate(rotation);g.scale(size/ch.head[2],size/ch.head[2]);g.translate(-ch.head[2]/2,-ch.head[3]/2);g.beginPath();ch.points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();g.clip();g.drawImage(source,...ch.head,0,0,ch.head[2],ch.head[3]);g.restore()}
function portraits(){document.querySelectorAll('[data-art]').forEach(c=>crop(c,c.dataset.art.split(',').map(Number)));document.querySelectorAll('[data-portrait]').forEach(c=>crop(c,chars[+c.dataset.portrait].crop));document.querySelectorAll('[data-head]').forEach(c=>{c.width=220;c.height=250;head(c.getContext('2d'),+c.dataset.head,110,125,195)});const l=$('#logo');if(l)crop(l,[15,65,244,151]);const sad=$('#sad');if(sad){crop(sad,[13,1033,164,201]);if(selected!==0){const g=sad.getContext('2d');head(g,selected,165,120,225)}}}
function menu(){state='menu';$('#hud').hidden=true;screen.dataset.view='menu';screen.innerHTML=`<section class="page menu"><button class="settings" data-action="settings" aria-label="Ajustes de sonido">${art([212,40,41,43])}</button><canvas class="logo" id="logo" aria-label="Grupo Estrella Flappy Guardia Código Rojo"></canvas><div class="menu-scene">${art([7,210,248,237])}<span class="sr-only">Emergencia. Mismas personas, mismas locuras, mejores guardias.</span></div><nav class="nav">${btn('ready','JUGAR','',true)}${btn('characters','PERSONAJES')}${btn('records','RÉCORDS')}${btn('instructions','INSTRUCCIONES')}${btn('credits','CRÉDITOS')}</nav><div class="menu-bottom">${art([0,652,76,142],'coffee-art','Café, turno, equipo, vida')}${art([143,699,113,96],'note-art','La guardia también se disfruta')}</div></section>`;portraits()}
function characters(){state='characters';screen.dataset.view='characters';screen.innerHTML=`<section class="page character-page">${top('SELECCIONÁ<br>TU PERSONAJE')}<p class="subtitle">Cada guardia tiene su estilo ♡</p><div class="cards">${chars.map((c,i)=>`<button class="card ${i===selected?'selected':''}" data-select="${i}" aria-label="${c.name}" aria-pressed="${i===selected}">${art([[281,144,115,175],[402,145,113,174],[281,327,114,172],[402,327,112,172]][i])}</button>`).join('')}</div><div class="panel character-info"><h2>${chars[selected].name.toUpperCase()}</h2><p>“${chars[selected].line}”</p><div class="stats">${['♧ Velocidad','♧ Flotación','♧ Control'].map((label,i)=>`<div class="stat"><span>${label}</span><div class="bar"><i style="width:${chars[selected].stats[i]}%"></i></div></div>`).join('')}</div></div><p class="saved-choice"><span>✓</span> Personaje predeterminado</p>${btn('ready','CONTINUAR','',true)}</section>`;portraits()}
function best(){return records.reduce((n,r)=>Math.max(n,r.score),0)}
function recordsPage(){state='records';screen.dataset.view='records';const ranking=[...records].sort((a,b)=>b.score-a.score).slice(0,10);screen.innerHTML=`<section class="page records-page">${top('🏆 RÉCORDS')}<div class="rank-tabs"><span>ESTE DISPOSITIVO</span><button data-action="editname">MI NOMBRE ✎</button></div><div class="table-wrap"><table><thead><tr><th>#</th><th>NOMBRE</th><th>PERSONAJE</th><th>PTS</th></tr></thead><tbody>${Array.from({length:10},(_,i)=>{const r=ranking[i];return r?`<tr class="${r.name===name?'mine':''}"><td>${i+1}</td><td>${escape(r.name)}</td><td><span class="rank-character"><canvas data-head="${Math.max(0,chars.findIndex(c=>c.name===r.character))}"></canvas>${escape(r.character)}</span></td><td><b>${r.score}</b></td></tr>`:`<tr><td>${i+1}</td><td class="vacant" colspan="2">${i===0?'Tu próxima guardia empieza acá':'—'}</td><td>—</td></tr>`}).join('')}</tbody></table></div><div class="record-boxes"><div class="panel">MI RÉCORD<strong>🏆 ${best()}</strong></div><div class="panel">MIS PUNTOS<strong>★ ${score}</strong></div></div><p class="small">Récords guardados en este navegador</p>${btn('menu','VOLVER AL MENÚ')}</section>`;portraits()}
function instructions(){state='instructions';screen.dataset.view='instructions';screen.innerHTML=`<section class="page instruction-page">${top('INSTRUCCIONES')}${art([541,849,233,461],'instruction-sheet','Tocá para saltar. Evitá las jeringas. Sumá puntos. Superá tu récord. Elegí tu personaje. Ajustá sonido y música. ¡Disfrutá!')}${art([558,1310,198,184],'instruction-note','Mismas personas, mismas locuras, mejores guardias')}<p class="small">PC: espacio o ↑ · Pausa: P<br>Pasar jeringas: +1 · Corazón: +3</p>${btn('ready','JUGAR','',true)}</section>`;portraits()}
function credits(){state='credits';screen.dataset.view='credits';screen.innerHTML=`<section class="page credits-page">${top('CRÉDITOS')}${art([810,850,198,444],'credits-sheet','Desarrollo: Grupo Estrella Games. Diseño y arte: inspirado en el día a día de la guardia. Idea original: Amir. Agradecimientos a todo el equipo que hace la guardia más llevadera.')}${art([798,1306,209,201],'credits-footer','Café, turno, equipo, vida. Grupo Estrella Flappy Guardia Código Rojo')}${btn('menu','VOLVER AL MENÚ')}<span class="version">v2.0</span></section>`;portraits()}
function reset(){score=0;hearts=0;elapsed=0;obstacles=[];particles=[];spawn=1.45;player={x:W*.29,y:H*.46,vy:0};$('#score').textContent=0;$('#hearts').textContent='♥ 0';shake=0}
function ready(){state='ready';screen.dataset.view='ready';reset();$('#hud').hidden=true;readyAt=performance.now();screen.innerHTML=`<section class="page ready-page"><button class="back" data-action="menu" aria-label="Volver al menú">‹</button><div class="ready-character"><canvas data-head="${selected}"></canvas><span class="tap-ripple"></span></div><div class="ready"><h2>¡VAMOS, ${chars[selected].name.toUpperCase()}!</h2><p>Tocá para saltar<br>y pasá entre las jeringas.</p>${btn('start','EMPEZAR','',true)}<p class="small">Espacio o ↑ en computadora</p></div></section>`;portraits()}
function start(){screen.dataset.view='playing';audioInit();state='playing';screen.innerHTML='';$('#hud').hidden=false;flap()}
function flap(){if(state!=='playing')return;player.vy=-chars[selected].jump;tone(640,.085,.04,'sine');for(let i=0;i<4;i++)particles.push({x:player.x-17,y:player.y+8,vx:-40-Math.random()*60,vy:Math.random()*50-25,life:.55,total:.55,kind:'heart'})}
function pause(){if(state!=='playing')return;state='paused';pausePage()}
function pausePage(){screen.dataset.view='pause';screen.innerHTML=`<section class="page pause-page">${art([879,88,67,91],'pause-coffee','Una taza de café')}<h1 class="pause-title">${state==='settings'?'AJUSTES':'PAUSA'}</h1><p>Un respiro también<br>es parte de la guardia ♡</p><nav class="nav">${state==='settings'?'':btn('resume','CONTINUAR','',true)}${state==='settings'?'':`<button class="sprite-button" data-action="ready" aria-label="Reiniciar">${art(sprites.restart)}</button>`}${toggle('sound','Sonido')}${toggle('music','Música')}${btn('menu','VOLVER AL MENÚ')}</nav>${art([868,632,139,162],'pause-note','Disciplina hoy, mejores pacientes')}</section>`;portraits()}
function resume(){screen.dataset.view='playing';state='playing';screen.innerHTML='';last=performance.now()}
function gameover(){if(state!=='playing')return;state='dying';shake=11;tone(170,.3,.09,'triangle');if(navigator.vibrate)navigator.vibrate(70);const prev=best();records.push({name:name.trim()||chars[selected].name,character:chars[selected].name,score,date:Date.now()});records.sort((a,b)=>b.score-a.score);records=records.slice(0,20);persist();setTimeout(()=>{if(state!=='dying')return;state='over';$('#hud').hidden=true;screen.dataset.view='over';screen.innerHTML=`<section class="page over-page">${art([22,868,225,77],'gameover-art','Game over')}<div class="result"><canvas id="sad"></canvas><div class="numbers"><small>PUNTOS</small><strong>${score}</strong><small>🏆 RÉCORD</small><strong>${best()}</strong></div></div><p class="over-quote">“CASI…<br>LA PRÓXIMA ES MEJOR” ♡</p>${score>prev?'<p class="new-record">¡NUEVO RÉCORD! 🏆</p>':''}<nav class="nav">${btn('ready','JUGAR DE NUEVO','',true)}${btn('menu','VOLVER AL MENÚ')}</nav>${art([23,1417,215,102],'fall-note','Caer también es parte del turno')}</section>`;portraits()},450)}
function addScore(n){score+=n;$('#score').animate?.([{transform:'scale(1.3)',color:'#ffea74'},{transform:'scale(1)',color:'#fff'}],{duration:230});$('#score').textContent=score;tone(n===3?988:880,.12,.055)}
function addObstacle(){const gap=Math.max(174,Math.min(222,H*.29))-Math.min(25,elapsed*.35);const margin=Math.min(155,H*.22);const center=margin+gap/2+Math.random()*Math.max(0,H-2*margin-gap);obstacles.push({x:W+50,center,gap,passed:false,heart:Math.random()>.3,collected:false});spawn=Math.max(1.38,1.85-elapsed*.004)}
function update(dt){elapsed+=dt;const ch=chars[selected];player.vy+=ch.gravity*dt;player.y+=player.vy*dt;spawn-=dt;if(spawn<=0)addObstacle();const speed=123+Math.min(52,elapsed*.65)+(ch.stats[0]-60)*.16;const radius=16-(ch.stats[2]-50)*.035;
for(const o of obstacles){o.x-=speed*dt;const top=o.center-o.gap/2,bottom=o.center+o.gap/2;if(!o.passed&&o.x+26<player.x-radius){o.passed=true;addScore(1)}if(o.heart&&!o.collected&&Math.hypot(player.x-o.x,player.y-o.center)<radius+14){o.collected=true;hearts++;$('#hearts').textContent='♥ '+hearts;addScore(3);for(let i=0;i<12;i++)particles.push({x:o.x,y:o.center,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*160,life:.8,total:.8,kind:'heart'})}if(player.x+radius>o.x-19&&player.x-radius<o.x+19&&(player.y-radius<top||player.y+radius>bottom)){gameover();return}}
obstacles=obstacles.filter(o=>o.x>-65);if(player.y-radius<0||player.y+radius>H){gameover();return}}
// The supplied illustration is sampled directly. Polygon masks preserve the original faces.
function syringe(x,y,length,flip){if(length<1)return;ctx.save();ctx.translate(x,y);if(flip)ctx.rotate(Math.PI);ctx.scale(.95,length/241);ctx.translate(-31,0);ctx.beginPath();[[24,0],[28,0],[30,40],[35,42],[35,63],[44,71],[47,86],[47,198],[59,198],[59,208],[43,211],[43,241],[17,241],[17,211],[0,208],[0,198],[4,198],[4,85],[9,72],[18,64],[18,42],[23,40]].forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();ctx.drawImage(source,582,413,62,241,0,0,62,241);ctx.restore()}
function scenery(rect,points,x,y,w,h){ctx.save();ctx.translate(x,y);ctx.scale(w/rect[2],h/rect[3]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();ctx.drawImage(source,...rect,0,0,rect[2],rect[3]);ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);if(!['playing','paused','dying','ready'].includes(state))return;ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88}const wash=ctx.createLinearGradient(0,0,0,H);wash.addColorStop(0,'#00203828');wash.addColorStop(1,'#02182a65');ctx.fillStyle=wash;ctx.fillRect(0,0,W,H);
// Original monitor and paper sign are scenery; only syringes collide.
ctx.save();ctx.globalAlpha=.94;scenery([688,406,87,135],[[8,8],[87,1],[87,118],[63,120],[65,126],[84,129],[83,135],[17,135],[17,130],[43,126],[43,121],[5,119],[1,112],[1,19]],W-122,H*.53,122,189);scenery([540,660,111,126],[[1,10],[90,0],[111,112],[15,125]],14,H-174,125,142);ctx.restore();
for(const o of obstacles){const t=o.center-o.gap/2,b=o.center+o.gap/2;syringe(o.x,t,t+16,true);syringe(o.x,b,H-b+16,false);if(o.heart&&!o.collected){ctx.fillStyle='#ff294f';ctx.font='27px Arial';ctx.textAlign='center';ctx.shadowColor='#ff385c';ctx.shadowBlur=16;ctx.fillText('♥',o.x,o.center+9+Math.sin(time*4)*3);ctx.shadowBlur=0}}
for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.total);ctx.fillStyle=p.kind==='heart'?'#ff3c63':'#9eefff';if(p.kind==='heart'){ctx.font='16px Arial';ctx.fillText('♥',p.x,p.y)}else{ctx.beginPath();ctx.arc(p.x,p.y,2.5,0,Math.PI*2);ctx.fill()}}ctx.globalAlpha=1;
if(player&&state!=='ready'){ctx.shadowColor='#00121b';ctx.shadowBlur=8;head(ctx,selected,player.x,player.y,60,Math.max(-.35,Math.min(.8,player.vy*.0016)));ctx.shadowBlur=0}ctx.restore()}
function loop(now){const dt=Math.min((now-last)/1000||0,1/30);last=now;time+=dt;if(state==='playing')update(dt);if(state==='dying'&&player){player.vy+=700*dt;player.y+=player.vy*dt}if(state==='playing'||state==='dying'){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}draw();requestAnimationFrame(loop)}
screen.addEventListener('click',e=>{const sel=e.target.closest('[data-select]');audioInit();if(sel){selected=+sel.dataset.select;persist();tone(780);characters();return}const b=e.target.closest('[data-action]');if(!b)return;tone(440,.055,.035);const a=b.dataset.action;const actions={menu,characters,records:recordsPage,instructions,credits,ready,start,resume,settings:()=>{state='settings';pausePage()},editname:()=>{screen.innerHTML=`<section class="page">${top('TU NOMBRE')}<div class="panel"><label for="playername">Nombre para tus récords</label><input id="playername" maxlength="18" value="${escape(name)}" autocomplete="nickname"></div>${btn('records','RÉCORDS')}</section>`;portraits()}};if(actions[a])actions[a]();else if(a==='sound'||a==='music'){if(a==='sound')sound=!sound;else music=!music;persist();pausePage()}});
screen.addEventListener('input',e=>{if(e.target.id==='playername'){name=e.target.value;persist()}});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();audioInit();flap()});$('#pause').addEventListener('click',pause);
document.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();if(e.repeat)return;audioInit();if(state==='playing')flap();else if(state==='ready'&&performance.now()-readyAt>150)start()}if(e.code==='KeyP'||e.code==='Escape'){if(state==='playing')pause();else if(state==='paused')resume()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();if(audio?.state==='running')audio.suspend()}else if(audio?.state==='suspended')audio.resume().catch(()=>{})});
source.onload=()=>{menu();requestAnimationFrame(loop)};source.onerror=()=>{screen.innerHTML='<section class="page"><h1>Falta el arte del juego</h1><p>Subí también la carpeta assets junto a index.html.</p></section>'};if(source.complete&&source.naturalWidth){source.onload();source.onload=null}
})();
